resolver: lts-12.26
packages:
- .
- location: 
    git: https://github.com/ucla-pls/reduce.git
    commit:  ef72213e8159f3f4a0414ec6bdec3195f1f5f752
    subdirs:
      - reduce
      - reduce-util
  extra-dep: true
- location: 
    git: https://github.com/ucla-pls/jvmhs.git
    subdirs:
      - jvmhs
    commit: 8468ee042b2e04fd387ad92213fbb68805dd903c
  extra-dep: true
extra-deps: 
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
- jvm-binary-0.6.1
- dirtree-0.1.0
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
