resolver: lts-17.11
packages:
- .
extra-deps:
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
- jvm-binary-0.10.0
- dirtree-0.1.3
- git: https://github.com/ucla-pls/jvmhs.git
  commit: 9143907131a5062c9a52c34cee60776a96b9ea1f
- git: https://github.com/ucla-pls/reduce.git
  commit: d15322dbe00f75b1a0dac4a92bb111688b555db3
  subdirs:
    - reduce
    - reduce-util
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
