resolver: lts-17.11
packages:
- .
extra-deps:
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
- jvm-binary-0.10.0
- dirtree-0.1.3
- git: https://github.com/ucla-pls/jvmhs.git
  commit: 18865087d573e23057ce3102b90cb8a1c607e1fd
- git: https://github.com/ucla-pls/reduce.git
  commit: b3ed58e1bd233140b1285b3ffbfbe7061709b416
  subdirs:
    - reduce
    - reduce-util
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
