resolver: lts-12.26
packages:
- .
extra-deps:
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
- jvm-binary-0.7.0
- dirtree-0.1.0
- git: https://github.com/ucla-pls/jvmhs.git
  subdirs:
    - jvmhs
  commit: 29890cea56693dd25a1b5978bdd4d8827ba8c9e3
- git: https://github.com/ucla-pls/reduce.git
  commit: b12fa6519d1ad20c85ed5be1177f7e7610aafd93
  subdirs:
    - reduce
    - reduce-util
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
